-- ============================================================
-- 9952 — scheduled ADMIN MESSAGES to every subscriber (session 020)
--
-- The user's ask, with their own example text: "I want to be able to schedule
-- an 'Admin message' that posts into the ad queue. For example ... 'Are you
-- liking The Plain Exchange? Feel free to call 330-960-7170 and leave a voice
-- message with feedback!'" — then, asked how it should behave: "it would send
-- out to all subscribers, in an individual message, and it would send only
-- during active hours."
--
-- So it is NOT a line riding an ad batch (that is what business sponsors are).
-- It is its own text, to every SMS subscriber, and it obeys the send window
-- exactly like an ad does — nothing at nine at night, nothing on a Sunday,
-- nothing after five on a Saturday.
--
-- send_after is the EARLIEST it may go, not an exact appointment. The window,
-- the cron tick and the segment budget all decide the real moment, so a
-- message scheduled for 6am Sunday goes out Monday morning rather than
-- silently missing its slot. Statuses: 'scheduled' -> 'sent', or 'canceled'.
--
-- Delivery deliberately reuses the digest outbox rather than sending inline:
-- the blocklist, the rolling segment budget, paced release, retries and the
-- resumable drain are all already there and all already correct. A broadcast
-- that invented its own sending path would have to re-earn every one of them.
--
-- Re-runnable, per repo convention (pasted into the Supabase SQL editor).
-- ============================================================

create table if not exists admin_messages (
  id bigint generated by default as identity primary key,
  body text not null,
  -- Earliest send time. The window and the cron decide the actual moment.
  send_after timestamptz not null default now(),
  status text not null default 'scheduled'
    check (status in ('scheduled', 'sent', 'canceled')),
  -- The digest row its outbox rows hang off, once composed. Null until sent.
  digest_id bigint references digests (id),
  recipients integer not null default 0,
  segments integer not null default 0,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table admin_messages is
  'Operator broadcasts to every SMS subscriber: own message, send-window only.';

-- The cron asks one question every few minutes: is anything due? Keep it cheap.
create index if not exists admin_messages_due_idx
  on admin_messages (send_after)
  where status = 'scheduled';

alter table admin_messages enable row level security;

-- Deny-by-default, like every other table: the service role bypasses RLS and
-- is the only thing that touches this. No policy is the point.
