-- 9972 — the call log for the call-in card line (/api/voice).
--
-- "I want to know when someone calls, how long they stay on the call and who
-- called" (user, session 016). One row per inbound call, keyed by Twilio's
-- CallSid so every later stage of the same call updates the same row.
--
-- Re-runnable: every statement is guarded.

create table if not exists call_log (
  id bigint generated by default as identity primary key,
  -- Twilio's CallSid: the identity of the call across all of its webhooks.
  call_sid text not null,
  -- 10-digit caller, when it is a normal US number (blocked/withheld = null).
  from_phone text,
  to_phone text,
  -- How the call ended up being handled. Widened as the flow does its thing:
  -- ringing -> answered | attendant -> card_saved | card_failed | voicemail.
  outcome text not null default 'ringing',
  -- Total seconds, authoritative, from Twilio's call status callback; before
  -- that arrives it holds the bridged-conversation duration, if any.
  duration_seconds integer,
  -- Set when a member's card was saved on this call, or the failure reason.
  detail text,
  recording_url text,
  created_at timestamptz not null default now(),
  ended_at timestamptz
);

-- One row per call: every stage upserts on this.
create unique index if not exists call_log_call_sid_key on call_log (call_sid);
-- The admin page reads newest-first.
create index if not exists call_log_created_at_idx on call_log (created_at desc);
-- "Every call from this number", from the member view.
create index if not exists call_log_from_phone_idx on call_log (from_phone);

alter table call_log enable row level security;
