-- ============================================================
-- The Plain Exchange — initial schema
--
-- Access model: the Next.js server talks to Postgres with the
-- service-role key only. RLS is ENABLED on every table with NO
-- policies, which means anon/authenticated API keys can read and
-- write nothing; the service role bypasses RLS. Do not add
-- policies without deciding the client-access story first.
-- ============================================================

create extension if not exists citext;

-- ---------- enums ----------

create type ad_status as enum ('pending', 'approved', 'rejected', 'sold', 'expired');
create type rejection_kind as enum ('benign', 'violation');
create type ledger_kind as enum ('grant', 'purchase', 'spend', 'refund', 'adjustment');
create type digest_channel as enum ('sms', 'email');
create type digest_item_kind as enum ('new', 'bump');
create type bump_status as enum ('queued', 'sent', 'cancelled');
create type message_direction as enum ('inbound', 'outbound');
create type message_channel as enum ('sms', 'mms', 'email');

-- ---------- users ----------
-- One row per person. Phone is the seller/SMS identity; email-only
-- subscribers have phone NULL (spec: selling requires a phone).

create table users (
  id uuid primary key default gen_random_uuid(),
  phone text unique check (phone ~ '^[0-9]{10}$'),
  email citext unique,
  password_hash text,
  county text not null default 'holmes',
  free_ads integer not null default 3,
  subscribed_at timestamptz,        -- SMS digest opt-in
  email_subscribed_at timestamptz,  -- email edition opt-in
  offense_count integer not null default 0,
  posting_banned_at timestamptz,    -- 3 strikes: blocks AD/BUMP/BUYCREDIT only
  full_blocked_at timestamptz,      -- rare full block (admin toggle)
  stripe_customer_id text,
  preferred_slots smallint[],       -- future per-user digest times; unused in v1
  created_at timestamptz not null default now(),
  constraint users_reachable check (phone is not null or email is not null)
);

comment on table users is 'Accounts, keyed by internal id; phone and email both optional-but-unique (at least one required).';

-- ---------- ads ----------
-- Public ad numbers are the identity values, starting at 1001.
-- body = display text as approved (admin may lightly edit);
-- original_body = exactly what the seller submitted (audit).

create table ads (
  id bigint generated by default as identity (start with 1001) primary key,
  user_id uuid not null references users (id),
  original_body text not null,
  body text not null,
  status ad_status not null default 'pending',
  county text not null default 'holmes',
  flagged boolean not null default false,  -- word-filter hit; sorted first in review
  rejection_kind rejection_kind,
  rejected_reason text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  expires_at timestamptz,
  sold_at timestamptz
);

create index ads_public_idx on ads (status, approved_at desc);
create index ads_user_idx on ads (user_id);
create index ads_review_idx on ads (created_at) where status = 'pending';

-- ---------- ad photos ----------
-- v1 keeps one photo per ad (position 0); schema allows more.

create table ad_photos (
  id bigint generated always as identity primary key,
  ad_id bigint not null references ads (id) on delete cascade,
  src text not null,   -- storage public URL (or site-relative path for seeds)
  width integer,
  height integer,
  alt text,
  position integer not null default 0
);

create index ad_photos_ad_idx on ad_photos (ad_id);

-- ---------- credits ----------
-- Append-only. Balance = sum(delta). Never update or delete rows.

create table credit_ledger (
  id bigint generated always as identity primary key,
  user_id uuid not null references users (id),
  delta integer not null,
  kind ledger_kind not null,
  note text not null,
  ref text,  -- e.g. Stripe payment intent / invoice id
  created_at timestamptz not null default now()
);

create index credit_ledger_user_idx on credit_ledger (user_id, created_at desc);

comment on table credit_ledger is 'Append-only credit history; the balance is the sum of deltas. Free-ad passes live on users.free_ads and appear here only as delta-0 notes.';

-- ---------- sign-in codes ----------

create table verification_codes (
  phone text primary key,
  code_hash text not null,
  expires_at timestamptz not null,
  attempts integer not null default 0,
  dev_echo text,  -- plaintext echo, populated only while no SMS provider is configured
  created_at timestamptz not null default now()
);

create table code_requests (
  id bigint generated always as identity primary key,
  phone text not null,
  requested_at timestamptz not null default now()
);

create index code_requests_phone_idx on code_requests (phone, requested_at desc);

-- ---------- digests ----------

create table digests (
  id bigint generated always as identity primary key,
  channel digest_channel not null,
  county text not null default 'holmes',
  scheduled_for timestamptz not null,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  unique (channel, county, scheduled_for)  -- idempotency: a slot runs once
);

create table digest_items (
  digest_id bigint not null references digests (id) on delete cascade,
  ad_id bigint not null references ads (id),
  kind digest_item_kind not null default 'new',
  position integer not null default 0,
  primary key (digest_id, ad_id)
);

-- ---------- bumps ----------
-- Free for now (config), unlimited per ad — but only one QUEUED at a time.

create table bumps (
  id bigint generated always as identity primary key,
  ad_id bigint not null references ads (id) on delete cascade,
  status bump_status not null default 'queued',
  requested_at timestamptz not null default now(),
  digest_id bigint references digests (id)
);

create index bumps_queue_idx on bumps (status, requested_at);
create unique index bumps_one_queued_per_ad on bumps (ad_id) where status = 'queued';

-- ---------- message audit log ----------
-- Absolutely every message, both directions, both channels.

create table messages (
  id bigint generated always as identity primary key,
  direction message_direction not null,
  channel message_channel not null,
  user_id uuid references users (id),
  address text not null,  -- phone number or email address
  body text,
  media jsonb,            -- inbound MMS attachments, outbound photo refs
  provider_id text,       -- Telnyx / email-provider message id
  provider_status text,   -- delivery status from webhooks
  digest_id bigint references digests (id),
  created_at timestamptz not null default now()
);

create index messages_user_idx on messages (user_id, created_at desc);
create index messages_created_idx on messages (created_at desc);
create index messages_provider_idx on messages (provider_id);

-- ---------- moderation ----------

create table offenses (
  id bigint generated always as identity primary key,
  user_id uuid not null references users (id),
  ad_id bigint references ads (id),
  note text not null,
  created_at timestamptz not null default now()
);

create index offenses_user_idx on offenses (user_id);

create table word_filter (
  id bigint generated always as identity primary key,
  word citext not null unique,
  auto_reject boolean not null default false,  -- false = flag for review only
  created_at timestamptz not null default now()
);

-- ---------- commerce & config ----------

create table packs (
  id text primary key,
  credits integer not null,
  price_cents integer not null,
  active boolean not null default true,
  position integer not null default 0
);

create table config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

comment on table config is 'Every admin-tunable number and string: digest slots, credit costs, caps, expiry days, support number, templates.';

-- ---------- RLS: deny-by-default ----------

alter table users enable row level security;
alter table ads enable row level security;
alter table ad_photos enable row level security;
alter table credit_ledger enable row level security;
alter table verification_codes enable row level security;
alter table code_requests enable row level security;
alter table digests enable row level security;
alter table digest_items enable row level security;
alter table bumps enable row level security;
alter table messages enable row level security;
alter table offenses enable row level security;
alter table word_filter enable row level security;
alter table packs enable row level security;
alter table config enable row level security;

-- ---------- storage ----------
-- Ad photos are public on the website by design (spec Q15/Q16):
-- the gate is on contact info, not pictures.

insert into storage.buckets (id, name, public)
values ('ad-photos', 'ad-photos', true)
on conflict (id) do nothing;
